2017-07-28 12:13:01.057 [error] <0.713.0> ** Node 'vgtpc_gw@36.36.36.90' not responding **
** Removing (timedout) connection **
2017-07-29 10:26:11.476 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 10:57:31.884 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 11:01:41.911 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 11:13:21.981 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 11:25:02.051 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 11:33:52.104 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 11:38:02.129 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 11:40:32.144 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 14:09:43.050 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 14:09:43.050 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 14:15:33.085 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 14:15:33.085 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 14:23:13.141 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 14:25:23.163 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 14:29:13.186 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 14:31:23.200 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 15:59:23.748 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 16:26:23.912 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 16:54:24.092 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 17:14:34.309 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 17:21:24.350 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 17:27:14.385 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 17:30:44.410 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 17:36:04.442 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 17:39:04.460 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 17:40:14.467 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 17:43:14.485 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 17:46:24.504 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 17:48:04.514 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 17:52:14.571 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 17:56:54.611 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 18:00:25.000 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.90', delete from tbl_diam_gw_node
2017-07-29 18:00:35.004 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-31 14:37:52.590 [error] <0.686.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-31 14:40:02.605 [error] <0.686.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.80', delete from tbl_diam_gw_node
2017-07-31 14:43:02.623 [error] <0.686.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-31 14:47:16.255 [error] <0.690.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-31 14:51:16.320 [error] <0.690.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.80', delete from tbl_diam_gw_node
2017-07-31 14:56:46.359 [error] <0.690.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-31 15:01:31.189 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-31 15:03:31.202 [error] <0.688.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.80', delete from tbl_diam_gw_node
2017-07-31 15:11:02.822 [error] <0.690.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-31 15:14:27.713 [error] <0.690.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-31 15:18:37.738 [error] <0.690.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-31 15:23:17.775 [error] <0.690.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-31 15:27:58.855 [error] <0.710.0> [DIAM_GW] diam_handler_in:55- Node PGWPCP 'vpgwcp1@36.36.36.90' is died, can not send msg to PGWCP
2017-07-31 15:28:05.831 [error] <0.727.0> [DIAM_GW] diam_callback:102- Error: timeout
2017-07-31 15:30:02.863 [error] <0.690.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-31 15:31:12.875 [error] <0.690.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.80', delete from tbl_diam_gw_node
2017-07-31 15:33:44.634 [error] <0.690.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-31 15:35:14.643 [error] <0.690.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.80', delete from tbl_diam_gw_node
2017-07-31 16:01:43.360 [error] <0.690.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-31 16:04:23.379 [error] <0.690.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.80', delete from tbl_diam_gw_node
2017-07-31 16:05:03.287 [error] <0.741.0> ** Node 'vpgwcp2@36.36.36.80' not responding **
** Removing (timedout) connection **
2017-07-31 16:06:43.393 [error] <0.690.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-31 16:49:03.132 [error] <0.690.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-07-31 17:03:13.248 [error] <0.690.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp2@36.36.36.80', delete from tbl_diam_gw_node
2017-07-31 17:03:43.124 [error] <0.825.0> ** Node 'vpgwcp2@36.36.36.80' not responding **
** Removing (timedout) connection **
2017-08-01 15:27:36.769 [error] <0.918.0> [DIAM_GW] diam_callback:102- Error: timeout
2017-08-01 15:37:20.136 [error] <0.3119.0> [DIAM_GW] diam_callback:102- Error: timeout
2017-08-01 15:41:33.233 [error] <0.3613.0> [DIAM_GW] diam_callback:102- Error: timeout
2017-08-01 15:50:44.697 [error] <0.5701.0> [DIAM_GW] diam_callback:102- Error: failover
2017-08-01 15:51:43.620 [error] <0.699.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-08-01 15:54:17.683 [error] <0.1207.0> [DIAM_GW] diam_callback:102- Error: failover
2017-08-01 15:57:22.292 [error] <0.1961.0> [DIAM_GW] diam_callback:102- Error: failover
2017-08-01 16:26:18.603 [error] <0.8967.0> [DIAM_GW] diam_callback:102- Error: failover
2017-08-01 16:51:24.814 [error] <0.14203.0> [DIAM_GW] diam_callback:102- Error: timeout
2017-08-01 17:01:27.576 [error] <0.696.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-08-01 17:14:27.657 [error] <0.696.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-08-01 17:35:27.818 [error] <0.696.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-08-01 17:39:07.843 [error] <0.696.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-08-01 17:42:57.876 [error] <0.696.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-08-01 17:47:57.910 [error] <0.696.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-06 10:21:34.788 [error] <0.692.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-06 10:25:34.812 [error] <0.692.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-06 10:29:04.838 [error] <0.692.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-06 10:33:04.862 [error] <0.692.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-09 14:34:00.838 [error] <0.701.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-09 14:45:12.868 [error] <0.4508.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 14:45:30.907 [error] <0.701.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-09 15:01:06.645 [error] <0.8322.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:02:06.646 [error] <0.8564.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:03:06.653 [error] <0.8806.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:04:06.652 [error] <0.9048.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:05:06.656 [error] <0.9286.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:06:06.656 [error] <0.9528.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:07:06.658 [error] <0.9770.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:08:06.658 [error] <0.10012.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:09:06.661 [error] <0.10254.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:10:06.662 [error] <0.10496.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:11:06.661 [error] <0.10738.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:12:06.663 [error] <0.10980.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:13:06.665 [error] <0.11222.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:14:06.665 [error] <0.11464.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:15:06.667 [error] <0.11706.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:16:06.667 [error] <0.11948.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:17:06.667 [error] <0.12190.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:18:06.668 [error] <0.12432.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:19:06.669 [error] <0.12674.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:20:06.670 [error] <0.12916.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:21:06.672 [error] <0.13158.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:22:06.674 [error] <0.13400.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:23:06.674 [error] <0.13642.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:24:06.676 [error] <0.13884.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:25:06.677 [error] <0.14126.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:26:06.677 [error] <0.14368.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:27:06.678 [error] <0.14610.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:28:06.679 [error] <0.14852.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:29:06.681 [error] <0.15094.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:30:06.683 [error] <0.15332.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:31:06.682 [error] <0.15574.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:32:06.682 [error] <0.15816.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:33:06.686 [error] <0.16058.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:34:06.684 [error] <0.16300.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:35:06.687 [error] <0.16542.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:36:06.688 [error] <0.16784.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:37:06.689 [error] <0.17026.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:38:06.690 [error] <0.17268.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:39:06.690 [error] <0.17510.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:40:06.691 [error] <0.17752.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:41:06.692 [error] <0.17994.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:42:06.692 [error] <0.18236.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:43:06.693 [error] <0.18474.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:44:06.694 [error] <0.18716.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:45:06.697 [error] <0.18958.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:46:06.697 [error] <0.19200.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:47:06.699 [error] <0.19442.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:48:06.699 [error] <0.19684.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:49:06.702 [error] <0.19926.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:50:06.701 [error] <0.20168.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:51:06.701 [error] <0.20410.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:52:06.702 [error] <0.20652.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:53:06.704 [error] <0.20894.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:54:06.706 [error] <0.21136.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:55:06.708 [error] <0.21378.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-09 15:56:06.707 [error] <0.21620.0> ** Connection attempt from disallowed node 'vpgwcp1@36.36.36.90' ** 
2017-09-27 17:40:06.037 [error] <0.699.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-27 17:44:02.149 [error] <0.698.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-28 08:42:39.742 [error] <0.699.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-28 08:50:49.791 [error] <0.699.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-28 09:13:29.979 [error] <0.699.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-28 09:15:39.993 [error] <0.699.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-28 09:36:10.174 [error] <0.699.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-28 10:41:10.577 [error] <0.699.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-28 10:53:10.649 [error] <0.699.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-28 10:58:30.681 [error] <0.699.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-28 11:01:00.696 [error] <0.699.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-28 11:04:30.717 [error] <0.699.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-28 11:28:10.906 [error] <0.699.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-09-28 11:45:11.033 [error] <0.699.0> [DIAM_GW] node_check:57- Timeout with PGWPCP='vpgwcp1@36.36.36.90', delete from tbl_diam_gw_node
2017-10-04 16:05:44.017 [error] <0.720.0> [DIAM_GW] diam_handler_in:54- Not found mappingNode with Key="diam_session;1567638246;4;vpgwcp1@19.19.19.19",0
2017-10-04 16:06:58.111 [error] <0.720.0> [DIAM_GW] diam_handler_in:54- Not found mappingNode with Key="diam_seesion;1559632244;3;vEMU_PCRF@29.19.19.130",0
2017-10-04 16:07:43.256 [error] <0.720.0> [DIAM_GW] diam_handler_in:54- Not found mappingNode with Key="diam_seesion;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-04 16:08:08.232 [error] <0.720.0> [DIAM_GW] diam_handler_in:54- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-04 16:13:44.390 [error] <0.720.0> [DIAM_GW] diam_handler_in:54- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 08:26:33.197 [error] <0.720.0> [DIAM_GW] diam_handler_in:54- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 08:28:28.958 [error] <0.720.0> [DIAM_GW] diam_handler_in:54- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 08:30:07.680 [error] <0.720.0> [DIAM_GW] diam_handler_in:54- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 09:23:32.912 [error] <0.720.0> [DIAM_GW] diam_handler_in:54- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 09:26:40.520 [error] <0.720.0> [DIAM_GW] diam_handler_in:54- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 09:27:25.618 [error] <0.720.0> [DIAM_GW] diam_handler_in:54- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 09:42:23.558 [error] <0.720.0> [DIAM_GW] diam_handler_in:54- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 09:50:45.405 [error] <0.720.0> [DIAM_GW] diam_handler_in:54- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 09:58:02.788 [error] <0.720.0> [DIAM_GW] diam_handler_in:54- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 10:05:47.193 [error] <0.720.0> [DIAM_GW] diam_handler_in:54- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 10:21:31.169 [error] <0.720.0> [DIAM_GW] diam_handler_in:54- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 11:05:46.771 [error] <0.720.0> [DIAM_GW] diam_handler_in:54- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 11:41:04.900 [error] <0.720.0> [DIAM_GW] diam_handler_in:54- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 15:51:14.883 [error] <0.720.0> [DIAM_GW] diam_handler_in:61- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 15:55:29.044 [error] <0.720.0> [DIAM_GW] diam_handler_in:61- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 16:27:24.209 [error] <0.720.0> [DIAM_GW] diam_handler_in:61- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 16:33:30.129 [error] <0.720.0> [DIAM_GW] diam_handler_in:61- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 17:10:32.357 [error] <0.720.0> [DIAM_GW] diam_handler_in:61- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-05 17:55:57.847 [error] <0.718.0> [DIAM_GW] diam_handler_in:61- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-06 08:05:48.825 [error] <0.718.0> [DIAM_GW] diam_handler_in:61- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-06 08:23:19.260 [error] <0.718.0> [DIAM_GW] diam_handler_in:61- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-06 10:27:48.252 [error] <0.718.0> [DIAM_GW] diam_handler_in:61- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-06 10:28:21.217 [error] <0.1099.0> [DIAM_GW] diam_handler_in:61- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-06 14:21:41.033 [error] <0.669.0> diameter: failure from peer_up callback
    {diam_callback,peer_up,2}

2017-10-06 14:21:41.033 [error] <0.657.0> Supervisor diameter_peer_fsm_sup had child diameter_peer_fsm started with {diameter_peer_fsm,start_link,undefined} at <0.1143.0> exit with reason killed in context child_terminated
2017-10-06 14:22:09.969 [error] <0.669.0> diameter: failure from peer_up callback
    {diam_callback,peer_up,2}

2017-10-06 14:22:09.969 [error] <0.657.0> Supervisor diameter_peer_fsm_sup had child diameter_peer_fsm started with {diameter_peer_fsm,start_link,undefined} at <0.1206.0> exit with reason killed in context child_terminated
2017-10-06 14:22:39.637 [error] <0.669.0> diameter: failure from peer_up callback
    {diam_callback,peer_up,2}

2017-10-06 14:22:39.637 [error] <0.657.0> Supervisor diameter_peer_fsm_sup had child diameter_peer_fsm started with {diameter_peer_fsm,start_link,undefined} at <0.1211.0> exit with reason killed in context child_terminated
2017-10-06 14:23:10.116 [error] <0.669.0> diameter: failure from peer_up callback
    {diam_callback,peer_up,2}

2017-10-06 14:23:10.116 [error] <0.657.0> Supervisor diameter_peer_fsm_sup had child diameter_peer_fsm started with {diameter_peer_fsm,start_link,undefined} at <0.1216.0> exit with reason killed in context child_terminated
2017-10-06 15:00:47.384 [error] <0.1217.0> ERROR: Could not find 'wxe_driver.so' in: /home/hieubt11/SGW_CP/Code_/vDIAM_GW/_rel/vdiam_gw_release/lib/wx-1.6.1/priv
2017-10-06 15:00:47.385 [error] <0.1217.0> CRASH REPORT Process <0.1217.0> with 0 neighbours exited with reason: {load_driver,"No driver found"} in wxe_util:priv_dir/2 line 263 in gen_server:init_it/6 line 352
2017-10-06 15:00:47.385 [error] <0.1216.0> CRASH REPORT Process <0.1216.0> with 0 neighbours exited with reason: {load_driver,"No driver found"} in wxe_util:priv_dir/2 line 263 in gen_server:init_it/6 line 352
2017-10-06 15:00:47.385 [error] <0.1215.0> CRASH REPORT Process observer with 0 neighbours exited with reason: {load_driver,"No driver found"} in wxe_server:start/1 line 65 in wx_object:init_it/6 line 350
2017-10-06 15:24:04.441 [error] <0.1197.0> CRASH REPORT Process <0.1197.0> with 0 neighbours exited with reason: bad argument in call to erlang:register(observer, <0.1197.0>) in observer_wx:init/1 line 95
2017-10-06 15:49:05.185 [error] <0.719.0> [DIAM_GW] diam_handler_in:61- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-06 15:59:59.980 [error] <0.719.0> [DIAM_GW] diam_handler_in:61- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-06 16:14:14.415 [error] <0.719.0> [DIAM_GW] diam_handler_in:61- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-06 16:17:25.058 [error] <0.717.0> [DIAM_GW] diam_handler_in:61- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-06 16:23:57.212 [error] <0.708.0> [DIAM_GW] diam_handler_in:61- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-06 16:24:52.607 [error] <0.708.0> [DIAM_GW] diam_handler_in:61- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-06 17:47:44.097 [error] <0.708.0> [DIAM_GW] diam_handler_in:61- Not found mappingNode with Key="diam_session;1559632244;3;vemu_pcrf@29.19.19.130",0
2017-10-07 11:28:01.175 [error] <0.675.0> Supervisor diam_sup_2 had child diam_handler_in started with diam_handler_in:start_link() at undefined exit with reason ok in context start_error
2017-10-07 11:28:01.175 [error] <0.674.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason {shutdown,{failed_to_start_child,diam_handler_in,ok}} in context start_error
2017-10-07 11:28:01.176 [error] <0.673.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,{shutdown,{failed_to_start_child,diam_handler_in,ok}}}} in context start_error
2017-10-07 11:28:01.176 [error] <0.661.0> CRASH REPORT Process <0.661.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,{shutdown,{failed_to_start_child,diam_handler_in,ok}}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 11:29:51.538 [error] <0.679.0> CRASH REPORT Process <0.679.0> with 0 neighbours exited with reason: no function clause matching diam_handler_in:init(null) line 46 in gen_server:init_it/6 line 352
2017-10-07 11:29:51.539 [error] <0.677.0> Supervisor diam_sup_2 had child diam_handler_in started with diam_handler_in:start_link() at undefined exit with reason no function clause matching diam_handler_in:init(null) line 46 in context start_error
2017-10-07 11:29:51.539 [error] <0.675.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason {shutdown,{failed_to_start_child,diam_handler_in,{function_clause,[{diam_handler_in,init,[null],[{file,"src/diameter/diam_handler_in.erl"},{line,46}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}} in context start_error
2017-10-07 11:29:51.540 [error] <0.674.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,{shutdown,{failed_to_start_child,diam_handler_in,{function_clause,[{diam_handler_in,init,[null],[{file,"src/diameter/diam_handler_in.erl"},{line,46}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}}} in context start_error
2017-10-07 11:29:51.541 [error] <0.661.0> CRASH REPORT Process <0.661.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,{shutdown,{failed_to_start_child,diam_handler_in,{function_clause,[{diam_handler_in,init,[null],[{file,"src/diameter/diam_handler_in.erl"},{line,46}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 11:45:40.804 [error] <0.679.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason {'EXIT',{undef,[{diam_sup,start_link,[diam_sup_2],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}} in context start_error
2017-10-07 11:45:40.804 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,{'EXIT',{undef,[{diam_sup,start_link,[diam_sup_2],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}} in context start_error
2017-10-07 11:45:40.804 [error] <0.661.0> CRASH REPORT Process <0.661.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,{'EXIT',{undef,[{diam_sup,start_link,[diam_sup_2],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}}}},{vdiam_gw_app,start,...}} in application_master:init/4 line 134
2017-10-07 14:03:31.390 [error] <0.685.0> Supervisor pmip_sup had child gtpmhandle started with pmip_receive_handle:start_link() at undefined exit with reason {already_started,<0.684.0>} in context start_error
2017-10-07 14:03:31.390 [error] <0.675.0> Supervisor vdiam_gw_sup had child pmip started with pmip_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,gtpmhandle,{already_started,<0.684.0>}}} in context start_error
2017-10-07 14:03:31.391 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,pmip,{shutdown,{failed_to_start_child,gtpmhandle,{already_started,<0.684.0>}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 14:10:50.232 [error] <0.681.0> gen_server diam_handler_in terminated with reason: no function clause matching diam_handler_in:terminate({bad_return_value,{normaly,{state}}}, {state}) line 264
2017-10-07 14:10:50.232 [error] <0.681.0> CRASH REPORT Process diam_handler_in with 0 neighbours exited with reason: no function clause matching diam_handler_in:terminate({bad_return_value,{normaly,{state}}}, {state}) line 264 in gen_server:terminate/7 line 814
2017-10-07 14:10:50.233 [error] <0.678.0> Supervisor diam_sup had child diam_handler_in started with diam_handler_in:start_link() at <0.681.0> exit with reason no function clause matching diam_handler_in:terminate({bad_return_value,{normaly,{state}}}, {state}) line 264 in context child_terminated
2017-10-07 14:13:35.356 [error] <0.682.0> gen_server diam_handler_in terminated with reason: no function clause matching diam_handler_in:terminate({bad_return_value,{normaly,{state}}}, {state}) line 52
2017-10-07 14:13:35.356 [error] <0.682.0> CRASH REPORT Process diam_handler_in with 0 neighbours exited with reason: no function clause matching diam_handler_in:terminate({bad_return_value,{normaly,{state}}}, {state}) line 52 in gen_server:terminate/7 line 814
2017-10-07 14:13:35.357 [error] <0.678.0> Supervisor diam_sup had child diam_handler_in started with diam_handler_in:start_link() at <0.682.0> exit with reason no function clause matching diam_handler_in:terminate({bad_return_value,{normaly,{state}}}, {state}) line 52 in context child_terminated
2017-10-07 14:15:03.761 [error] <0.681.0> gen_server diam_handler_in terminated with reason: bad return value: {normaly,{state}}
2017-10-07 14:15:03.761 [error] <0.681.0> CRASH REPORT Process diam_handler_in with 0 neighbours exited with reason: bad return value: {normaly,{state}} in gen_server:terminate/7 line 826
2017-10-07 14:15:03.762 [error] <0.678.0> Supervisor diam_sup had child diam_handler_in started with diam_handler_in:start_link() at <0.681.0> exit with reason bad return value: {normaly,{state}} in context child_terminated
2017-10-07 14:28:42.395 [error] <0.698.0> [DIAM_GW] diam_sup:57- Exception in start_diam_handler_in: {noproc,{gen_server,call,[diam_sup_1,{start_child,{"diam_in_1507400922395289849",{diam_handler_in,start_link,[]},temporary,5000,worker,[diam_handler_in]}},infinity]}} [{gen_server,call,3,[{file,"gen_server.erl"},{line,212}]},{diam_sup,start_diam_handler_in,0,[{file,"src/diameter/diam_sup.erl"},{line,46}]},{diam_sup,send_msg_diam_incoming,1,[{file,"src/diameter/diam_sup.erl"},{line,63}]},{diameter_traffic,'-send_request/4-fun-0-',6,[{file,"base/diameter_traffic.erl"},{line,1233}]}]
2017-10-07 14:30:07.219 [error] <0.1108.0> [DIAM_GW] diam_sup:57- Exception in start_diam_handler_in: {noproc,{gen_server,call,[diam_sup_2,{start_child,{"diam_in_1507401007219628378",{diam_handler_in,start_link,[]},temporary,5000,worker,[diam_handler_in]}},infinity]}} [{gen_server,call,3,[{file,"gen_server.erl"},{line,212}]},{diam_sup,start_diam_handler_in,0,[{file,"src/diameter/diam_sup.erl"},{line,46}]},{diam_sup,send_msg_diam_incoming,1,[{file,"src/diameter/diam_sup.erl"},{line,63}]},{diameter_traffic,'-send_request/4-fun-0-',6,[{file,"base/diameter_traffic.erl"},{line,1233}]}]
2017-10-07 14:31:15.774 [error] <0.676.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason {'EXIT',{undef,[{diam_sup,start_link,[diam_sup_2],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}} in context start_error
2017-10-07 14:31:15.775 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,{'EXIT',{undef,[{diam_sup,start_link,[diam_sup_2],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}} in context start_error
2017-10-07 14:31:15.775 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,{'EXIT',{undef,[{diam_sup,start_link,[diam_sup_2],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}}}},{vdiam_gw_app,start,...}} in application_master:init/4 line 134
2017-10-07 14:34:15.362 [error] <0.681.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link() at undefined exit with reason {already_started,<0.682.0>} in context start_error
2017-10-07 14:34:15.363 [error] <0.677.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,{already_started,<0.682.0>}}} in context start_error
2017-10-07 14:34:15.363 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,{already_started,<0.682.0>}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 14:38:08.559 [error] <0.698.0> [DIAM_GW] diam_sup:57- Exception in start_diam_handler_in: {noproc,{gen_server,call,[diam_sup_1,{start_child,{"diam_in_1507401488558968653",{diam_handler_in,start_link,[]},temporary,5000,worker,[diam_handler_in]}},infinity]}} [{gen_server,call,3,[{file,"gen_server.erl"},{line,212}]},{diam_sup,start_diam_handler_in,0,[{file,"src/diameter/diam_sup.erl"},{line,46}]},{diam_sup,send_msg_diam_incoming,1,[{file,"src/diameter/diam_sup.erl"},{line,63}]},{diameter_traffic,'-send_request/4-fun-0-',6,[{file,"base/diameter_traffic.erl"},{line,1233}]}]
2017-10-07 14:39:00.874 [error] <0.681.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link() at undefined exit with reason {already_started,<0.682.0>} in context start_error
2017-10-07 14:39:00.874 [error] <0.680.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,{already_started,<0.682.0>}}} in context start_error
2017-10-07 14:39:00.875 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,{already_started,<0.682.0>}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 14:41:11.899 [error] <0.677.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link() at undefined exit with reason {already_started,<0.679.0>} in context start_error
2017-10-07 14:41:11.900 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,{already_started,<0.679.0>}}} in context start_error
2017-10-07 14:41:11.900 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,{already_started,<0.679.0>}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 14:42:14.345 [error] <0.676.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link() at undefined exit with reason {already_started,<0.677.0>} in context start_error
2017-10-07 14:42:14.345 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,{already_started,<0.677.0>}}} in context start_error
2017-10-07 14:42:14.346 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,{already_started,<0.677.0>}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 14:43:15.513 [error] <0.677.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link() at undefined exit with reason {already_started,<0.679.0>} in context start_error
2017-10-07 14:43:15.513 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,{already_started,<0.679.0>}}} in context start_error
2017-10-07 14:43:15.513 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,{already_started,<0.679.0>}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 14:44:36.107 [error] <0.677.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link() at undefined exit with reason {already_started,<0.678.0>} in context start_error
2017-10-07 14:44:36.107 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,{already_started,<0.678.0>}}} in context start_error
2017-10-07 14:44:36.107 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,{already_started,<0.678.0>}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 14:44:36.108 [error] <0.676.0> Supervisor diameter_tcp_transport_sup had child diameter_tcp started with diameter_tcp:start_link() at undefined exit with reason {shutdown,parent} in context shutdown_error
2017-10-07 14:45:14.915 [error] <0.698.0> [DIAM_GW] diam_sup:57- Exception in start_diam_handler_in: {noproc,{gen_server,call,[diam_sup_1,{start_child,{"diam_in_1507401914915270975",{diam_handler_in,start_link,[]},temporary,5000,worker,[diam_handler_in]}},infinity]}} [{gen_server,call,3,[{file,"gen_server.erl"},{line,212}]},{diam_sup,start_diam_handler_in,0,[{file,"src/diameter/diam_sup.erl"},{line,46}]},{diam_sup,send_msg_diam_incoming,1,[{file,"src/diameter/diam_sup.erl"},{line,63}]},{diameter_traffic,'-send_request/4-fun-0-',6,[{file,"base/diameter_traffic.erl"},{line,1233}]}]
2017-10-07 14:51:51.534 [error] <0.677.0> CRASH REPORT Process <0.677.0> with 0 neighbours exited with reason: no function clause matching supervisor:check_startspec(0, [{child,undefined,diam_sup_1,{diam_sup,start_link,[]},permanent,5000,supervisor,[diam_sup]},{child,...}]) line 1288 in gen_server:init_it/6 line 352
2017-10-07 14:51:51.534 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason no function clause matching supervisor:check_startspec(0, [{child,undefined,diam_sup_1,{diam_sup,start_link,[]},permanent,5000,supervisor,[diam_sup]},{child,...}]) line 1288 in context start_error
2017-10-07 14:51:51.535 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{function_clause,[{supervisor,check_startspec,[0,[{child,undefined,diam_sup_1,{diam_sup,start_link,[]},permanent,5000,supervisor,[diam_sup]},{child,undefined,diam_sup_2,{diam_sup,start_link,[]},permanent,5000,supervisor,[diam_sup]}]],[{file,"supervisor.erl"},{line,1288}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,305}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.er..."},...]}]}}},...} in application_master:init/4 line 134
2017-10-07 14:52:11.112 [error] <0.681.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link() at undefined exit with reason {already_started,<0.683.0>} in context start_error
2017-10-07 14:52:11.112 [error] <0.680.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,{already_started,<0.683.0>}}} in context start_error
2017-10-07 14:52:11.112 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,{already_started,<0.683.0>}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 14:55:15.798 [error] <0.686.0> Supervisor diam_sup_1 had child gtpmhandle started with pmip_receive_handle:start_link() at undefined exit with reason {already_started,<0.685.0>} in context start_error
2017-10-07 14:55:15.798 [error] <0.678.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link(diam_sup_1) at undefined exit with reason {shutdown,{failed_to_start_child,gtpmhandle,{already_started,<0.685.0>}}} in context start_error
2017-10-07 14:55:15.799 [error] <0.676.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,{shutdown,{failed_to_start_child,gtpmhandle,{already_started,<0.685.0>}}}}} in context start_error
2017-10-07 14:55:15.799 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,{shutdown,{failed_to_start_child,gtpmhandle,{already_started,<0.685.0>}}}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 15:00:48.744 [error] <0.685.0> Supervisor diam_sup_1 had child gtpmhandle started with pmip_receive_handle:start_link() at undefined exit with reason {already_started,<0.684.0>} in context start_error
2017-10-07 15:00:48.745 [error] <0.677.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link(diam_sup_1) at undefined exit with reason {shutdown,{failed_to_start_child,gtpmhandle,{already_started,<0.684.0>}}} in context start_error
2017-10-07 15:00:48.745 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,{shutdown,{failed_to_start_child,gtpmhandle,{already_started,<0.684.0>}}}}} in context start_error
2017-10-07 15:00:48.746 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,{shutdown,{failed_to_start_child,gtpmhandle,{already_started,<0.684.0>}}}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 15:01:31.775 [error] <0.678.0> Supervisor diam_sup_2 had child gtpmhandle started with pmip_receive_handle:start_link() at undefined exit with reason {'EXIT',{undef,[{pmip_receive_handle,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}} in context start_error
2017-10-07 15:01:31.777 [error] <0.677.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason {shutdown,{failed_to_start_child,gtpmhandle,{'EXIT',{undef,[{pmip_receive_handle,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}} in context start_error
2017-10-07 15:01:31.778 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,{shutdown,{failed_to_start_child,gtpmhandle,{'EXIT',{undef,[{pmip_receive_handle,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}}}} in context start_error
2017-10-07 15:01:31.779 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,{shutdown,{failed_to_start_child,gtpmhandle,{'EXIT',{undef,[{pmip_receive_handle,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_li..."},...]}]}}}}}}}},...} in application_master:init/4 line 134
2017-10-07 15:03:40.801 [error] <0.686.0> Supervisor diam_sup_1 had child gtpmhandle started with pmip_receive_handle:start_link() at undefined exit with reason {already_started,<0.685.0>} in context start_error
2017-10-07 15:03:40.802 [error] <0.681.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link(diam_sup_1) at undefined exit with reason {shutdown,{failed_to_start_child,gtpmhandle,{already_started,<0.685.0>}}} in context start_error
2017-10-07 15:03:40.802 [error] <0.680.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,{shutdown,{failed_to_start_child,gtpmhandle,{already_started,<0.685.0>}}}}} in context start_error
2017-10-07 15:03:40.803 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,{shutdown,{failed_to_start_child,gtpmhandle,{already_started,<0.685.0>}}}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 15:05:59.548 [error] <0.686.0> Supervisor diam_sup_1 had child gtpmhandle started with pmip_receive_handle:start_link() at undefined exit with reason {already_started,<0.685.0>} in context start_error
2017-10-07 15:05:59.549 [error] <0.681.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link(diam_sup_1) at undefined exit with reason {shutdown,{failed_to_start_child,gtpmhandle,{already_started,<0.685.0>}}} in context start_error
2017-10-07 15:05:59.550 [error] <0.680.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,{shutdown,{failed_to_start_child,gtpmhandle,{already_started,<0.685.0>}}}}} in context start_error
2017-10-07 15:05:59.550 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,{shutdown,{failed_to_start_child,gtpmhandle,{already_started,<0.685.0>}}}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 15:06:58.312 [error] <0.681.0> Supervisor diam_pool_sup had child pool_sup started with diam_sup:start_link() at undefined exit with reason {'EXIT',{undef,[{diam_sup,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}} in context start_error
2017-10-07 15:06:58.313 [error] <0.680.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,pool_sup,{'EXIT',{undef,[{diam_sup,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}} in context start_error
2017-10-07 15:06:58.314 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,pool_sup,{'EXIT',{undef,[{diam_sup,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 15:07:33.811 [error] <0.685.0> Supervisor diam_sup_1 had child gtpmhandle started with pmip_receive_handle:start_link() at undefined exit with reason {already_started,<0.684.0>} in context start_error
2017-10-07 15:07:33.812 [error] <0.678.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link(diam_sup_1) at undefined exit with reason {shutdown,{failed_to_start_child,gtpmhandle,{already_started,<0.684.0>}}} in context start_error
2017-10-07 15:07:33.813 [error] <0.676.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,{shutdown,{failed_to_start_child,gtpmhandle,{already_started,<0.684.0>}}}}} in context start_error
2017-10-07 15:07:33.813 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,{shutdown,{failed_to_start_child,gtpmhandle,{already_started,<0.684.0>}}}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 15:41:04.624 [error] <0.677.0> Supervisor diam_sup_2 had child diam_sup_1 started with pmip_receive_handle:start_link() at undefined exit with reason {already_started,<0.680.0>} in context start_error
2017-10-07 15:41:04.624 [error] <0.676.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,{already_started,<0.680.0>}}} in context start_error
2017-10-07 15:41:04.625 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,{shutdown,{failed_to_start_child,diam_sup_1,{already_started,<0.680.0>}}}}} in context start_error
2017-10-07 15:41:04.625 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,{shutdown,{failed_to_start_child,diam_sup_1,{already_started,<0.680.0>}}}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 15:41:47.754 [error] <0.699.0> gen_server <0.699.0> terminated with reason: bad return value: {normaly,{state}}
2017-10-07 15:41:47.754 [error] <0.699.0> CRASH REPORT Process <0.699.0> with 0 neighbours exited with reason: bad return value: {normaly,{state}} in gen_server:terminate/7 line 826
2017-10-07 15:41:47.755 [error] <0.682.0> Supervisor diam_sup_1 had child "diam_in_1507405307754304964" started with {diam_handler_in,start_link,undefined} at <0.699.0> exit with reason bad return value: {normaly,{state}} in context child_terminated
2017-10-07 15:43:34.889 [error] <0.699.0> gen_server <0.699.0> terminated with reason: bad return value: {normaly,{state}}
2017-10-07 15:43:34.889 [error] <0.699.0> CRASH REPORT Process <0.699.0> with 0 neighbours exited with reason: bad return value: {normaly,{state}} in gen_server:terminate/7 line 826
2017-10-07 15:43:34.889 [error] <0.677.0> Supervisor diam_sup_1 had child "diam_in_1507405414888023005" started with {diam_handler_in,start_link,undefined} at <0.699.0> exit with reason bad return value: {normaly,{state}} in context child_terminated
2017-10-07 15:47:03.515 [error] <0.682.0> Supervisor diam_sup_2 had child process_1 started with pmip_receive_handle:start_link() at undefined exit with reason {already_started,<0.684.0>} in context start_error
2017-10-07 15:47:03.515 [error] <0.681.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason {shutdown,{failed_to_start_child,process_1,{already_started,<0.684.0>}}} in context start_error
2017-10-07 15:47:03.515 [error] <0.680.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,{shutdown,{failed_to_start_child,process_1,{already_started,<0.684.0>}}}}} in context start_error
2017-10-07 15:47:03.516 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,{shutdown,{failed_to_start_child,process_1,{already_started,<0.684.0>}}}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 15:48:06.359 [error] <0.679.0> Supervisor diam_sup_2 had child process_1 started with pmip_receive_handle:start_link() at undefined exit with reason {already_started,<0.683.0>} in context start_error
2017-10-07 15:48:06.359 [error] <0.677.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason {shutdown,{failed_to_start_child,process_1,{already_started,<0.683.0>}}} in context start_error
2017-10-07 15:48:06.359 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,{shutdown,{failed_to_start_child,process_1,{already_started,<0.683.0>}}}}} in context start_error
2017-10-07 15:48:06.360 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,{shutdown,{failed_to_start_child,process_1,{already_started,<0.683.0>}}}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 15:57:41.925 [error] <0.682.0> Supervisor diam_sup_2 had child process_1 started with pmip_receive_handle:start_link() at undefined exit with reason {already_started,<0.683.0>} in context start_error
2017-10-07 15:57:41.926 [error] <0.677.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason {shutdown,{failed_to_start_child,process_1,{already_started,<0.683.0>}}} in context start_error
2017-10-07 15:57:41.926 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,{shutdown,{failed_to_start_child,process_1,{already_started,<0.683.0>}}}}} in context start_error
2017-10-07 15:57:41.927 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,{shutdown,{failed_to_start_child,process_1,{already_started,<0.683.0>}}}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 16:01:54.589 [error] <0.680.0> Supervisor diam_sup_2 had child process_2 started with pmip_receive_handle:start_link(process_2) at undefined exit with reason {'EXIT',{undef,[{pmip_receive_handle,start_link,[process_2],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}} in context start_error
2017-10-07 16:01:54.592 [error] <0.677.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason {shutdown,{failed_to_start_child,process_2,{'EXIT',{undef,[{pmip_receive_handle,start_link,[process_2],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}} in context start_error
2017-10-07 16:01:54.593 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,{shutdown,{failed_to_start_child,process_2,{'EXIT',{undef,[{pmip_receive_handle,start_link,[process_2],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}}}} in context start_error
2017-10-07 16:01:54.593 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,{shutdown,{failed_to_start_child,process_2,{'EXIT',{undef,[{pmip_receive_handle,start_link,[process_2],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,...},...]}]}}}}}}}},...} in application_master:init/4 line 134
2017-10-07 16:02:48.032 [error] <0.679.0> Supervisor diam_sup_2 had child process_2 started with pmip_receive_handle:start_link(process_2) at undefined exit with reason {'EXIT',{undef,[{pmip_receive_handle,start_link,[process_2],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}} in context start_error
2017-10-07 16:02:48.032 [error] <0.676.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason {shutdown,{failed_to_start_child,process_2,{'EXIT',{undef,[{pmip_receive_handle,start_link,[process_2],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}} in context start_error
2017-10-07 16:02:48.033 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,{shutdown,{failed_to_start_child,process_2,{'EXIT',{undef,[{pmip_receive_handle,start_link,[process_2],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}}}} in context start_error
2017-10-07 16:02:48.034 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,{shutdown,{failed_to_start_child,process_2,{'EXIT',{undef,[{pmip_receive_handle,start_link,[process_2],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,...},...]}]}}}}}}}},...} in application_master:init/4 line 134
2017-10-07 16:13:35.339 [error] <0.682.0> CRASH REPORT Process <0.682.0> with 0 neighbours exited with reason: {bad_return,{diam_sup,init,[{ok,{{one_for_one,1,5},{process_2,{pmip_receive_handle,start_link,[process_2]},permanent,5000,worker,[pmip_receive_handle]}}},{ok,{{one_for_one,1,5},{process_1,{pmip_receive_handle,start_link,[process_1]},permanent,5000,worker,[pmip_receive_handle]}}}]}} in gen_server:init_it/6 line 344
2017-10-07 16:13:35.339 [error] <0.679.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason {bad_return,{diam_sup,init,[{ok,{{one_for_one,1,5},{process_2,{pmip_receive_handle,start_link,[process_2]},permanent,5000,worker,[pmip_receive_handle]}}},{ok,{{one_for_one,1,5},{process_1,{pmip_receive_handle,start_link,[process_1]},permanent,5000,worker,[pmip_receive_handle]}}}]}} in context start_error
2017-10-07 16:13:35.340 [error] <0.677.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,{bad_return,{diam_sup,init,[{ok,{{one_for_one,1,5},{process_2,{pmip_receive_handle,start_link,[process_2]},permanent,5000,worker,[pmip_receive_handle]}}},{ok,{{one_for_one,1,5},{process_1,{pmip_receive_handle,start_link,[process_1]},permanent,5000,worker,[pmip_receive_handle]}}}]}}}} in context start_error
2017-10-07 16:13:35.340 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,{bad_return,{diam_sup,init,[{ok,{{one_for_one,1,5},{process_2,{pmip_receive_handle,start_link,[process_2]},permanent,5000,worker,[pmip_receive_handle]}}},{ok,{{one_for_one,1,5},{process_1,{pmip_receive_handle,start_link,[process_1]},permanent,5000,worker,[pmip_receive_handle]}}}]}}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 16:17:05.578 [error] <0.676.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason diam_sup_2 in context start_error
2017-10-07 16:17:05.578 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,diam_sup_2}} in context start_error
2017-10-07 16:17:05.579 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,diam_sup_2}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 16:17:46.019 [error] <0.682.0> CRASH REPORT Process <0.682.0> with 0 neighbours exited with reason: bad argument in call to io:format(<0.663.0>, "Name", ['1507407466018965798']) in diam_sup:init/1 line 102
2017-10-07 16:17:46.019 [error] <0.676.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason diam_sup_2 in context start_error
2017-10-07 16:17:46.020 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,diam_sup_2}} in context start_error
2017-10-07 16:17:46.020 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,diam_sup_2}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 16:18:27.104 [error] <0.677.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason diam_sup_2 in context start_error
2017-10-07 16:18:27.104 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,diam_sup_2}} in context start_error
2017-10-07 16:18:27.105 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,diam_sup_2}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 16:20:50.878 [error] <0.677.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason diam_sup_2 in context start_error
2017-10-07 16:20:50.878 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,diam_sup_2}} in context start_error
2017-10-07 16:20:50.879 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,diam_sup_2}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 16:24:05.209 [error] <0.678.0> CRASH REPORT Process <0.678.0> with 0 neighbours exited with reason: no function clause matching diam_sup:get_diam_name(0.8777499570929067) line 112 in gen_server:init_it/6 line 352
2017-10-07 16:24:05.209 [error] <0.676.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason diam_sup_2 in context start_error
2017-10-07 16:24:05.210 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,diam_sup_2}} in context start_error
2017-10-07 16:24:05.210 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,diam_sup_2}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 16:25:03.228 [error] <0.677.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason diam_sup_2 in context start_error
2017-10-07 16:25:03.229 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,diam_sup_2}} in context start_error
2017-10-07 16:25:03.230 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,diam_sup_2}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 16:29:34.796 [error] <0.681.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link(diam_sup_1) at undefined exit with reason diam_sup_1 in context start_error
2017-10-07 16:29:34.796 [error] <0.676.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,diam_sup_1}} in context start_error
2017-10-07 16:29:34.797 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,diam_sup_1}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 16:31:32.406 [error] <0.681.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link(diam_sup_1) at undefined exit with reason diam_sup_1 in context start_error
2017-10-07 16:31:32.406 [error] <0.680.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,diam_sup_1}} in context start_error
2017-10-07 16:31:32.407 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,diam_sup_1}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 16:32:38.428 [error] <0.676.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link(diam_sup_1) at undefined exit with reason diam_sup_1 in context start_error
2017-10-07 16:32:38.428 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,diam_sup_1}} in context start_error
2017-10-07 16:32:38.428 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,diam_sup_1}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 16:33:46.326 [error] <0.678.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link(diam_sup_1) at undefined exit with reason diam_sup_1 in context start_error
2017-10-07 16:33:46.326 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,diam_sup_1}} in context start_error
2017-10-07 16:33:46.327 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,diam_sup_1}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 16:34:29.129 [error] <0.699.0> gen_server <0.699.0> terminated with reason: bad return value: {normaly,{state}}
2017-10-07 16:34:29.129 [error] <0.699.0> CRASH REPORT Process <0.699.0> with 0 neighbours exited with reason: bad return value: {normaly,{state}} in gen_server:terminate/7 line 826
2017-10-07 16:34:29.130 [error] <0.679.0> Supervisor diam_sup_1 had child "diam_in_1507408469127791532" started with {diam_handler_in,start_link,undefined} at <0.699.0> exit with reason bad return value: {normaly,{state}} in context child_terminated
2017-10-07 16:35:19.412 [error] <0.684.0> Supervisor diam_sup_1 had child process_519 started with pmip_receive_handle:start_link() at undefined exit with reason {already_started,<0.683.0>} in context start_error
2017-10-07 16:35:19.412 [error] <0.680.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link(diam_sup_1) at undefined exit with reason {shutdown,{failed_to_start_child,process_519,{already_started,<0.683.0>}}} in context start_error
2017-10-07 16:35:19.413 [error] <0.676.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,{shutdown,{failed_to_start_child,process_519,{already_started,<0.683.0>}}}}} in context start_error
2017-10-07 16:35:19.413 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,{shutdown,{failed_to_start_child,process_519,{already_started,<0.683.0>}}}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 16:36:55.016 [error] <0.678.0> CRASH REPORT Process <0.678.0> with 0 neighbours exited with reason: no function clause matching diam_sup:get_diam_name(undefined) line 112 in gen_server:init_it/6 line 352
2017-10-07 16:36:55.016 [error] <0.677.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason no function clause matching diam_sup:get_diam_name(undefined) line 112 in context start_error
2017-10-07 16:36:55.017 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,{function_clause,[{diam_sup,get_diam_name,[undefined],[{file,"src/diameter/diam_sup.erl"},{line,112}]},{diam_sup,init,1,[{file,"src/diameter/diam_sup.erl"},{line,101}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,287}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}} in context start_error
2017-10-07 16:36:55.017 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,{function_clause,[{diam_sup,get_diam_name,[undefined],[{file,"src/diameter/diam_sup.erl"},{line,112}]},{diam_sup,init,1,[{file,"src/diameter/diam_sup.erl"},{line,101}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,287}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 16:37:57.625 [error] <0.678.0> CRASH REPORT Process <0.678.0> with 0 neighbours exited with reason: no match of right hand value undefined in diam_sup:init/1 line 100 in gen_server:init_it/6 line 352
2017-10-07 16:37:57.626 [error] <0.676.0> Supervisor diam_pool_sup had child diam_sup_2 started with diam_sup:start_link(diam_sup_2) at undefined exit with reason no match of right hand value undefined in diam_sup:init/1 line 100 in context start_error
2017-10-07 16:37:57.626 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_2,{{badmatch,undefined},[{diam_sup,init,1,[{file,"src/diameter/diam_sup.erl"},{line,100}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,287}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}} in context start_error
2017-10-07 16:37:57.627 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_2,{{badmatch,undefined},[{diam_sup,init,1,[{file,"src/diameter/diam_sup.erl"},{line,100}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,287}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 16:37:57.628 [error] <0.680.0> Supervisor diameter_tcp_monitor_sup had child diameter_tcp started with diameter_tcp:start_link() at undefined exit with reason {shutdown,{'DOWN',#Ref<0.0.2.29>,process,<0.674.0>,{shutdown,{shutdown,<0.673.0>,application}}}} in context shutdown_error
2017-10-07 16:37:57.629 [error] <0.677.0> Supervisor diameter_tcp_transport_sup had child diameter_tcp started with diameter_tcp:start_link() at undefined exit with reason {shutdown,parent} in context shutdown_error
2017-10-07 16:42:36.848 [error] <0.684.0> Supervisor diam_sup_1 had child process_847713 started with pmip_receive_handle:start_link() at undefined exit with reason {already_started,<0.683.0>} in context start_error
2017-10-07 16:42:36.848 [error] <0.677.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link(diam_sup_1) at undefined exit with reason {shutdown,{failed_to_start_child,process_847713,{already_started,<0.683.0>}}} in context start_error
2017-10-07 16:42:36.849 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,{shutdown,{failed_to_start_child,process_847713,{already_started,<0.683.0>}}}}} in context start_error
2017-10-07 16:42:36.850 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,{shutdown,{failed_to_start_child,process_847713,{already_started,<0.683.0>}}}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 16:45:14.416 [error] <0.685.0> Supervisor diam_sup_1 had child process_416252 started with pmip_receive_handle:start_link() at undefined exit with reason {already_started,<0.683.0>} in context start_error
2017-10-07 16:45:14.417 [error] <0.677.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link(diam_sup_1) at undefined exit with reason {shutdown,{failed_to_start_child,process_416252,{already_started,<0.683.0>}}} in context start_error
2017-10-07 16:45:14.417 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,{shutdown,{failed_to_start_child,process_416252,{already_started,<0.683.0>}}}}} in context start_error
2017-10-07 16:45:14.417 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,{shutdown,{failed_to_start_child,process_416252,{already_started,<0.683.0>}}}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 17:10:56.604 [error] <0.680.0> Supervisor diam_sup_1 had child pmip started with pmip_receive_handle:start_link() at undefined exit with reason {'EXIT',{undef,[{pmip_receive_handle,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}} in context start_error
2017-10-07 17:10:56.605 [error] <0.677.0> Supervisor diam_pool_sup had child diam_sup_1 started with diam_sup:start_link(diam_sup_1) at undefined exit with reason {shutdown,{failed_to_start_child,pmip,{'EXIT',{undef,[{pmip_receive_handle,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}} in context start_error
2017-10-07 17:10:56.606 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_1,{shutdown,{failed_to_start_child,pmip,{'EXIT',{undef,[{pmip_receive_handle,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}}}} in context start_error
2017-10-07 17:10:56.606 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_1,{shutdown,{failed_to_start_child,pmip,{'EXIT',{undef,[{pmip_receive_handle,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},...]}]}}}}}}}},...} in application_master:init/4 line 134
2017-10-07 17:13:23.737 [error] <0.699.0> gen_server <0.699.0> terminated with reason: bad return value: {normaly,{state}}
2017-10-07 17:13:23.737 [error] <0.699.0> CRASH REPORT Process <0.699.0> with 0 neighbours exited with reason: bad return value: {normaly,{state}} in gen_server:terminate/7 line 826
2017-10-07 17:13:23.738 [error] <0.678.0> Supervisor diam_sup_1 had child "diam_in_1507410803736134786" started with {diam_handler_in,start_link,undefined} at <0.699.0> exit with reason bad return value: {normaly,{state}} in context child_terminated
2017-10-07 17:37:24.738 [error] <0.685.0> Supervisor diam_sup_7 had child pmip started with pmip_receive_handle:start_link(pmip) at undefined exit with reason {already_started,<0.684.0>} in context start_error
2017-10-07 17:37:24.739 [error] <0.676.0> Supervisor diam_pool_sup had child diam_sup_7 started with diam_sup:start_link(diam_sup_7) at undefined exit with reason {shutdown,{failed_to_start_child,pmip,{already_started,<0.684.0>}}} in context start_error
2017-10-07 17:37:24.739 [error] <0.675.0> Supervisor vdiam_gw_sup had child diam_pool_sup started with diam_pool_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,diam_sup_7,{shutdown,{failed_to_start_child,pmip,{already_started,<0.684.0>}}}}} in context start_error
2017-10-07 17:37:24.740 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,diam_pool_sup,{shutdown,{failed_to_start_child,diam_sup_7,{shutdown,{failed_to_start_child,pmip,{already_started,<0.684.0>}}}}}}},{vdiam_gw_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-10-07 17:39:01.679 [error] <0.699.0> gen_server <0.699.0> terminated with reason: bad return value: {normaly,{state}}
2017-10-07 17:39:01.679 [error] <0.699.0> CRASH REPORT Process <0.699.0> with 0 neighbours exited with reason: bad return value: {normaly,{state}} in gen_server:terminate/7 line 826
2017-10-07 17:39:01.679 [error] <0.677.0> Supervisor diam_sup_1 had child "diam_in_1507412341679264020" started with {diam_handler_in,start_link,undefined} at <0.699.0> exit with reason bad return value: {normaly,{state}} in context child_terminated
2017-10-08 06:24:06.932 [error] <0.662.0> [DIAM_GW] config_util:47- Exception in load_config: {{nodedown,'vNM_EPC@172.16.29.154'},{gen_server,call,[{nm_api_handler,'vNM_EPC@172.16.29.154'},{get_config,'vdiam_gw@29.19.19.19'}]}} [{gen_server,call,2,[{file,"gen_server.erl"},{line,204}]},{config_util,load_config,0,[{file,"src/util/config_util.erl"},{line,20}]},{vdiam_gw_app,start,2,[{file,"src/vdiam_gw_app.erl"},{line,18}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}], so read_config_from_file diam_gw.config
2017-10-08 06:24:06.934 [error] <0.662.0> [DIAM_GW] vdiam_gw_app:37- Exception in start vdiam_gw_app: {badmatch,{error,{1,erl_parse,["syntax error before: ",["For"]]}}} [{config_util,read_config_from_file,0,[{file,"src/util/config_util.erl"},{line,52}]},{vdiam_gw_app,start,2,[{file,"src/vdiam_gw_app.erl"},{line,18}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}]
2017-10-08 06:24:06.935 [error] <0.661.0> CRASH REPORT Process <0.661.0> with 0 neighbours exited with reason: bad return value ok from vdiam_gw_app:start(normal, []) in application_master:init/4 line 134
